- ldap.php
LDAP URL was parsed, but port setting not stored.
For ldaps:// connections, the port was then not applied because ldap_connect ignores the port parameter if a URL is used in the hostname.
> Port setting ignored / not applied

- authLdap.php
Hi,
if some attributes in the config screen are left empty, the search still tries to request them.
This leads to weird requests (e.g. ```SRCH attr=givenName sn mail 1.1```, where ```1.1``` is the result of the empty elements).
This patch removes those empty elements from the requested attributes array.
EmTeedee
> remove empty elements from requested attributes

- view/admin.phtml
This PR adds some javascript to remove the LDAP-Groupmapping-stuff
when no GroupMapping shall be used.
This simply hides the entries so they are not lost but simply not shown
> Adds Eyecandy to remove unneeded config-parts

- authLdap.php
- view/admin.phtml
Hi,
this fixes the issue with existing users' roles mentioned in #34
I also added an option to override existing roles with LDAP Groups (which is enabled by default as it's been the behaviour so far).
> retain exsiting user role, option for group override

- authLdap.php
This fixes issue #39
This PR adds an error log-entry as soon as a user tries to log in
using an email-address that already exists in the database.
> Adds an error to log on dupe mailaddress

- view/admin.phtml
Hi,
looks like the checkbox for `authLDAPGroupEnable` has creeped in twice.
The first one has the handling to hide the options for groups, so if I disable groups at the top, the options for groups (including the second checkbox to enable them) is hidden away.
But, that checkbox is still ticked and submitted, so groups remain enabled.
The only way to disable groups is to first uncheck the option at the bottom, then uncheck the same option at the top.
This fixes the issue by removing the bottom one of those checkboxes.
> Disabling groups is not working with second checkbox

- authLdap.php
Otherwise the credentials of the user trying to log in will be used and
that user might not be able to read the group-informations
This fixes #55
> Use the default-user to retrieve groups

- authLdap.php
Changed the lookup of meta_key = wp_capabilities within the authLdap_user_role to take custom prefixes into account instead of assuming 'wp_' prefix. Fixes #69
> Use proper WP prefix when looking up user roles

- authLdap.php
If you turn on debug messages with `define( 'WP_DEBUG', true );`, you will see a number of errors in this plugin. These commits fix 4 of those (the ones I saw on my WordPress 4.3 installation).
- registration.php is deprecated since WP 3.1 (check the file, it does nothing now)
- user levels are deprecated since WP 2.0 (use capabilities instead)
- proper check for existence of `$_POST['ldapOptionsSave']`
- set `$tChecked` variables to a blank string if false check, to avoid 'undefined variable' PHP errors
> Fixes for WP_DEBUG error messages

- authLdap.php
To mitigate the security issue of exposing a user's login name ( issue #72 ):
- Set user's nickname to their first_name (+ last_name if present)
- Set user's nicename to their first_name (+ last_name if present)
(the nicename is used in URL links and is therefore also exposed)
Examples:
- "John" gets nickname "john", nicename "john"
- "John Doe" gets nickname "John Doe", nicename "john_doe"
Also, don't override user's nickname if one already exists, allowing manual edit from the WP interface.
> Set user nickname and nicename to user's realname

- authLdap.php
This commit fixes the password-display on the users profile page. When
the user is authenticated via LDAP the password-dialog is not displayed
whereas on creating new users or for users that are not authenticated
via LDAP the password-fiel is displayed.
> Fixes password-display on profile-page

- authLdap.php
Until now a default address has been generated when no email-address
coulf be retrieved. This is not necessary any more and is therefore
removed
This addresses and fixes #93
> Removes generation of default-email-address

- authLdap.php
This PR disables the password-reset-link for LDAP-authenticated users.
This fixes #84. Fix thankfully provided by [chaplina](https://github.com/chaplina)
> Disables Password-reset for LDAP-Users

- authLdap.php
This email has been anoying for users that changed their password in the
LDAP and then logged into wordpress as wordpress noticed the change and
sent an email hat the password has been changed.
This will not happen with WP 4.3.0 anymore.
This has been reported by
[litinoveweedle](https://github.com/litinoveweedle) in issue #80
> Removes the password-changed Email to the user

- authLdap.php
This adds code that honors an already successfull authentication.
As the first parameter to the login-function is either "NULL" when no authentication attempt has happened or WP_Error when a previous login-attempt has failed or WP_User when a previous login-attempt already has been successfull. Therefore when the first parameter is an instance of WP_USer we now instantly return that instance without further processing.
This has been reported in issue #81 by [litinoveweedle](https://github.com/litinoveweedle)
> Adds acceptance for already authenticated user

- authLdap.php
- view/admin.phtml
When using memberof as the group attribute, the value contains a DN
which has comma in it.
Note: this possibly breaks compatibility with existing configs
> Use ; as separator for groups

- authLdap.php
This removes the deprecated ```wp_setcookie```-function. It should fix #98
> Removes deprecated cookie-function

- authLdap.php
> Fix for broken apostrophes causing PHP parser error (refs #133).

- authLdap.php
The 50 char cropping of the 'user_nicename' key in user_info was happening before the val;ue was computed from the first and last name attributes, possibly resulting in a string length > 50 chars.
This change simply moves the extant test to below the code block that may set the value.
> Delay length check on user_info['user_nicename']

- authLdap.php
- readme.txt
This PR adds support for using the plugin as authentication-backend for a MultiSite-environment.
It will no longer be possible to be used only for one site within a MultiSite-setup!
As this is a BC-break it will need to be included in a Major-version.
> Adds WPMU-support for login

- authLdap.php
- ldap.php
- src/LdapList.php
- view/admin.phtml
I have multiple wordpresses, which use a single ldap base.
Users have different rights in different WP installations.
I have a ou for each WP with user groups in those.
so i need to set the group-search base-dn for each WP installation to be different from the user-dn.
This patch adds a option to specify the search base in the ldap->search function. if none is specified, the search base is taken from the ldap-uri (same as before this patch).
_This is a redo of #163 using a feature branch (im sort of new to this branch thing)_
> allow to specify different base DN for group lookups

- authLdap.php
1. Add a `do_action` hook after successful login - which allows you to handle custom modifications when the user is authenticated.
1. Add a `apply_filters` hook for parameters retrieved from LDAP - which allows you to retrieve other parameters from LDAP then the preset ones.
> Add custom hooks

- authLdap.php
Call custom add_action hook after `is_wp_error()` check so the action always get's user ID (int) not `WP_Error`. 
Sorry for the mess, it was my mistake and it took me more than half a year to find it out.
> Fix: send success action after is_wp_error() check

- authLdap.php
Fixed a typo of successful, previously had an extra 'l' in it.
> Fixed typo successfull > successful

- authLdap.php
- view/admin.phtml
Closes #213 
It introduces a new option (the default leaves things working as they were) to use the user account to feach the different atributes of the user. Before the admin account was the one responsible for fetching those attributes.
WIP: Maybe change the name of the option, but I doesn't come one fit to mind.
> Allow querying with the user's credentials

- authLdap.php
As the filter is applied to fetch only the roles that the current user
can assign to another user - which is not aplicable to what we are doing
here - the list can become empty which will result in wrong information
being assigned.
Therefore we now simply use the WP_Roles content to define the order of
the roles to then use the first role.
This will (hopefully) fix #221
> Use unfiltered roles-list

- authLdap.php
A minor modification to authLdap.php for supporting using ‘dn’ in authLDAPGroupAttr.
> Allow to use 'dn' in authLDAPGroupAttr

- authLdap.php
WordPress allows multiple roles per user even though it doesn't have UI support and is widely used (for example in WooCommerce and other similar extensions) and we needed this functionality in the authLdap plugin.
I've added a new filter `authLdap_allow_mlutiple_roles`. If you pass `true`, authLdap will assign all mapped roles received from LDAP. Otherwise, it behaves as before. I would add a checkbox to settings instead, but not sure if it should be available to everyone (since there is default UI trouble).
To use this feature, simply add this line of code:
`add_filter('authLdap_allow_multiple_roles', '__return_true');`
> Allow multiple group/roles assignemenet

- authLdap.php
- view/admin.phtml
This allows to make sure the request did not come from a potentially mallicious side that didn't call the form before.
This addresses CVE-2023-41654
> Add nonce to option-form

- .github/workflows/behat.yml
- view/admin.phtml
This should eliminate the risk of injecting JS into form field values.
Adding backslashes or quotes in any of the fields will result in a backslash-escaped value. SHould these values be stored more than once the amount of backslashes will exponentially grow. This is a sideeffect of these values not being expected in the fields in the first place.
This should also fix CVE-2023-41655 as now injecting JS will no longer result in that being executed in the UI.
For more discussion around this CVE see
https://github.com/heiglandreas/authLdap/issues/237
> Escape Form-values

- authLdap.php
- readme.txt
For whatever reason the admin interface had an issue with an empty groups-setup as that was interpreted as string instead of an empty array.
Therefore we convert the empty string into an empty array.
> Fix broken admin interface

- .github/workflows/tests.yml
- phpcs-version-check.xml
- src/LoggedInUserToWpUser.php
- tests/Manager/LDAPBaseTest.php
THis allows me to find linting errors when ran against the different PHP-versions to not run into the issue that happened when using the sensitiveparameter attribute on PHP7.4
> Add php-lint

- .github/workflows/behat.yml
- dockersetup/Dockerfile_wordpress
- src/Manager/Ldap.php
- src/Wrapper/Ldap.php
- tests/LdapTest.php
- tests/LdapUriTest.php
- tests/Manager/LDAPBaseTest.php
They now also include diagnostic messages when those are available. Also the bind-error log now also includes the URI that it failed to bind to for better debugging.
This should fix #270
> Improve error messages
